// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26/1/2026, 11:19:12 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Projects/rnd/hajri/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/rnd/hajri/frontend/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/rnd/hajri/frontend/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/rnd/hajri/frontend/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/rnd/hajri/frontend/app/plugins/**/*.{js,ts,mjs}","C:/Projects/rnd/hajri/frontend/app/composables/**/*.{js,ts,mjs}","C:/Projects/rnd/hajri/frontend/app/utils/**/*.{js,ts,mjs}","C:/Projects/rnd/hajri/frontend/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/rnd/hajri/frontend/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/rnd/hajri/frontend/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Projects/rnd/hajri/frontend/app/app.config.{js,ts,mjs}","C:/Projects/rnd/hajri/frontend/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;